/* eslint-disable no-unused-vars */
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import InPageNavigation from "./InPageNavigation";

const MatchDetails = () => {
  let { id } = useParams();

  let FixedData = {
    matchInfo: {
      matchId: 46161,
      matchDescription: "56th Match",
      matchFormat: "T20",
      matchType: "league",
      complete: true,
      domestic: false,
      matchStartTimestamp: 1652104800000,
      matchCompleteTimestamp: 1652117400000,
      dayNight: true,
      year: 2022,
      dayNumber: 1,
      state: "complete",
      team1: {
        id: 62,
        name: "Mumbai Indians",
        playerDetails: [
          {
            id: 10276,
            name: "Ishan Kishan",
            fullName: "Ishan Kishan",
            nickName: "Ishan Kishan",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 62,
            battingStyle: "Left-hand bat",
            bowlingStyle: "",
            teamName: "Mumbai Indians",
            faceImageId: 226219,
          },
          {
            id: 576,
            name: "Rohit",
            fullName: "Rohit Sharma",
            nickName: "Rohit",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 170658,
          },
          {
            id: 14504,
            name: "Tilak Varma",
            fullName: "Tilak Varma",
            nickName: "Tilak Varma",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 226525,
          },
          {
            id: 13169,
            name: "Tim David",
            fullName: "Tim David",
            nickName: "Tim David",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Mumbai Indians",
            faceImageId: 226530,
          },
          {
            id: 657,
            name: "Pollard",
            fullName: "Kieron Pollard",
            nickName: "Pollard",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Mumbai Indians",
            faceImageId: 226283,
          },
          {
            id: 12337,
            name: "Ramandeep Singh ",
            fullName: "Ramandeep Singh ",
            nickName: "Ramandeep Singh ",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 13162,
            name: "Daniel Sams",
            fullName: "Daniel Sams",
            nickName: "Daniel Sams",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm fast-medium",
            teamName: "Mumbai Indians",
            faceImageId: 180315,
          },
          {
            id: 8796,
            name: "M Ashwin",
            fullName: "Murugan Ashwin",
            nickName: "Murugan Ashwin",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Mumbai Indians",
            faceImageId: 226412,
          },
          {
            id: 14190,
            name: "Kumar Kartikeya",
            fullName: "Kumar Kartikeya",
            nickName: "Kartikeya",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm chinaman",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 9311,
            name: "Bumrah",
            fullName: "Jasprit Bumrah",
            nickName: "Bumrah",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Mumbai Indians",
            faceImageId: 170685,
          },
          {
            id: 12226,
            name: "Riley Meredith",
            fullName: "Riley Meredith",
            nickName: "Meredith",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Mumbai Indians",
            faceImageId: 155663,
          },
          {
            id: 6327,
            name: "Unadkat",
            fullName: "Jaydev Unadkat",
            nickName: "Unadkat",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm fast-medium",
            teamName: "Mumbai Indians",
            faceImageId: 169793,
          },
          {
            id: 9785,
            name: "Fabian Allen",
            fullName: "Fabian Allen",
            nickName: "Fabian Allen",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Mumbai Indians",
            faceImageId: 170794,
          },
          {
            id: 10267,
            name: "Basil Thampi",
            fullName: "Basil Thampi",
            nickName: "Basil Thampi",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Mumbai Indians",
            faceImageId: 226469,
          },
          {
            id: 10947,
            name: "Anmolpreet Singh",
            fullName: "Anmolpreet Singh",
            nickName: "Anmolpreet Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 179867,
          },
          {
            id: 11631,
            name: "Sanjay Yadav",
            fullName: "Sanjay Yadav",
            nickName: "Sanjay Yadav",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 12627,
            name: "Markande",
            fullName: "Mayank Markande",
            nickName: "Markande",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Mumbai Indians",
            faceImageId: 226510,
          },
          {
            id: 13388,
            name: "Aryan Juyal",
            fullName: "Aryan Juyal",
            nickName: "Aryan Juyal",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Mumbai Indians",
            faceImageId: 156041,
          },
          {
            id: 13747,
            name: "Arjun Tendulkar",
            fullName: "Arjun Tendulkar",
            nickName: "Arjun Tendulkar",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm fast-medium",
            teamName: "Mumbai Indians",
            faceImageId: 154048,
          },
          {
            id: 14595,
            name: "Hrithik Shokeen",
            fullName: "Hrithik Shokeen",
            nickName: "Hrithik Shokeen",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 16584,
            name: "Rahul Buddhi",
            fullName: "Rahul Buddhi",
            nickName: "Rahul Buddhi",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 19243,
            name: "Tristan Stubbs",
            fullName: "Tristan Stubbs",
            nickName: "Tristan Stubbs",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Mumbai Indians",
            faceImageId: 182026,
          },
          {
            id: 20538,
            name: "Dewald Brevis",
            fullName: "Dewald Brevis",
            nickName: "Brevis",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 62,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Mumbai Indians",
            faceImageId: 226302,
          },
        ],
        shortName: "MI",
      },
      team2: {
        id: 63,
        name: "Kolkata Knight Riders",
        playerDetails: [
          {
            id: 1447,
            name: "Rahane",
            fullName: "Ajinkya Rahane",
            nickName: "Rahane",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171082,
          },
          {
            id: 10917,
            name: "Venkatesh Iyer",
            fullName: "Venkatesh Iyer",
            nickName: "Venkatesh Iyer",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226278,
          },
          {
            id: 9428,
            name: "Shreyas Iyer",
            fullName: "Shreyas Iyer",
            nickName: "Shreyas Iyer",
            captain: true,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171024,
          },
          {
            id: 9204,
            name: "Nitish Rana",
            fullName: "Nitish Rana",
            nickName: "Nitish Rana",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 171047,
          },
          {
            id: 10896,
            name: "Rinku Singh",
            fullName: "Rinku Singh",
            nickName: "Rinku Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 187877,
          },
          {
            id: 7736,
            name: "Russell",
            fullName: "Andre Russell",
            nickName: "Russell",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170821,
          },
          {
            id: 2276,
            name: "Narine",
            fullName: "Sunil Narine",
            nickName: "Narine",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 152654,
          },
          {
            id: 8846,
            name: "Jackson",
            fullName: "Sheldon Jackson",
            nickName: "Jackson",
            captain: false,
            role: "WK-Batsman",
            keeper: true,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 169694,
          },
          {
            id: 8095,
            name: "Cummins",
            fullName: "Pat Cummins",
            nickName: "Cummins",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170651,
          },
          {
            id: 1057,
            name: "Southee",
            fullName: "Tim Southee",
            nickName: "Southee",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170753,
          },
          {
            id: 12926,
            name: "Chakaravarthy",
            fullName: "Varun Chakaravarthy",
            nickName: "Chakaravarthy",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: false,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226220,
          },
          {
            id: 1858,
            name: "Umesh",
            fullName: "Umesh Yadav",
            nickName: "Umesh Yadav",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast",
            teamName: "Kolkata Knight Riders",
            faceImageId: 153874,
          },
          {
            id: 3007,
            name: "Nabi",
            fullName: "Mohammad Nabi",
            nickName: "Nabi",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170853,
          },
          {
            id: 7990,
            name: "Billings",
            fullName: "Sam Billings",
            nickName: "Billings",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 156173,
          },
          {
            id: 9500,
            name: "C Karunaratne",
            fullName: "Chamika Karunaratne",
            nickName: "Karunaratne",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 216499,
          },
          {
            id: 12640,
            name: "Pratham Singh",
            fullName: "Pratham Singh",
            nickName: "Pratham Singh",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 12813,
            name: "Abhijeet Tomar",
            fullName: "Abhijeet Tomar",
            nickName: "Abhijeet Tomar",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm offbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 19473,
            name: "Aman Hakim Khan",
            fullName: "Aman Hakim Khan",
            nickName: "Aman Hakim Khan",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 24261,
            name: "Ashok Sharma",
            fullName: "Ashok Sharma",
            nickName: "Ashok Sharma",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 24281,
            name: "Ramesh Kumar",
            fullName: "Ramesh Kumar",
            nickName: "Ramesh Kumar",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 9624,
            name: "Indrajith",
            fullName: "Baba Indrajith",
            nickName: "Indrajith",
            captain: false,
            role: "WK-Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm legbreak",
            teamName: "Kolkata Knight Riders",
            faceImageId: 226621,
          },
          {
            id: 1643,
            name: "Finch",
            fullName: "Aaron Finch",
            nickName: "Finch",
            captain: false,
            role: "Batsman",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Kolkata Knight Riders",
            faceImageId: 170630,
          },
          {
            id: 12344,
            name: "Anukul Roy",
            fullName: "Anukul Roy",
            nickName: "Anukul Roy",
            captain: false,
            role: "Batting Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Left-hand bat",
            bowlingStyle: "Left-arm orthodox",
            teamName: "Kolkata Knight Riders",
            faceImageId: 153915,
          },
          {
            id: 24729,
            name: "Harshit Rana",
            fullName: "Harshit Rana",
            nickName: "Harshit Rana",
            captain: false,
            role: "Bowler",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 182026,
          },
          {
            id: 12345,
            name: "Shivam Mavi",
            fullName: "Shivam Mavi",
            nickName: "Shivam Mavi",
            captain: false,
            role: "Bowling Allrounder",
            keeper: false,
            substitute: true,
            teamId: 63,
            battingStyle: "Right-hand bat",
            bowlingStyle: "Right-arm fast-medium",
            teamName: "Kolkata Knight Riders",
            faceImageId: 155147,
          },
        ],
        shortName: "KKR",
      },
      series: {
        id: 4061,
        name: "Indian Premier League 2022",
        seriesType: "IPL",
        startDate: 1652104800000,
        endDate: 1652117400000,
        seriesFolder: "2022_IPL",
        odiSeriesResult: "",
        t20SeriesResult: "",
        testSeriesResult: "",
        tournament: true,
      },
      umpire1: {
        id: 6864,
        name: "Chris Gaffaney",
        country: "NZ",
      },
      umpire2: {
        id: 10271,
        name: "Sadashiv Iyer",
        country: "IND",
      },
      umpire3: {
        id: 6841,
        name: "Bruce Oxenford",
        country: "AUS",
      },
      referee: {
        id: 9225,
        name: "Prakash Bhatt",
        country: "IND",
      },
      tossResults: {},
      result: {
        resultType: "win",
        winningTeam: "Kolkata Knight Riders",
        winningteamId: 63,
        winningMargin: 52,
        winByRuns: true,
        winByInnings: false,
      },
      venue: {
        id: 132,
        name: "Dr DY Patil Sports Academy",
        city: "Mumbai",
        country: "India",
        timezone: "",
        latitude: "",
        longitude: "",
      },
      status: "Kolkata Knight Riders won by 52 runs",
      playersOfTheMatch: [
        {
          id: 9311,
          name: "Bumrah",
          fullName: "Jasprit Bumrah",
          nickName: "Bumrah",
          captain: false,
          role: "Batsman",
          keeper: false,
          substitute: false,
          teamId: 0,
          battingStyle: " ",
          bowlingStyle: " ",
          teamName: " ",
          faceImageId: 170685,
        },
      ],
      playersOfTheSeries: [],
      revisedTarget: {},
      matchTeamInfo: [
        {
          battingTeamId: 63,
          battingTeamShortName: "KKR",
          bowlingTeamId: 62,
          bowlingTeamShortName: "MI",
        },
        {
          battingTeamId: 62,
          battingTeamShortName: "MI",
          bowlingTeamId: 63,
          bowlingTeamShortName: "KKR",
        },
      ],
      isMatchNotCovered: false,
      HYSEnabled: 1,
      livestreamEnabled: false,
      isFantasyEnabled: false,
      livestreamEnabledGeo: [],
      alertType: "",
      shortStatus: "KKR won",
      matchImageId: 379130,
    },
    venueInfo: {
      established: 2007,
      capacity: "60,000",
      knownAs: null,
      ends: "Media End, Pavilion End",
      city: "Navi Mumbai ",
      country: "India",
      timezone: "+05:30",
      homeTeam: null,
      floodlights: true,
      curator: null,
      profile: null,
      imageUrl:
        "http://i.cricketcb.com/i/stats/fth/540x303/venue/images/132.jpg",
      ground: "Dr DY Patil Sports Academy",
      groundLength: 0.0,
      groundWidth: 0.0,
      otherSports: null,
    },
    broadcastInfo: [],
  };

  // Data called froim the api frommthe useeffect hook
  let [data, setData] = useState([]);

  async function FetchMatchDetails() {
    const url = `https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/${id}`;
    const options = {
      method: "GET",
      headers: {
        "x-rapidapi-key": import.meta.env.VITE_API_KEY,
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
      },
    };

    try {
      const response = await fetch(url, options);
      const result = await response.json();
      setData(result);
      console.log(result);
    } catch (error) {
      console.error(error);
    }
  }

  useEffect(() => {
    FetchMatchDetails();
  }, []);

  return (
    <>
      <div className="bg-blue-600 text-xl font-medium text-center p-3 text-white">
        Match Details{" "}
      </div>
      {/* <InPageNavigation
        teams={[
          FixedData.matchInfo.team1.shortName,
          FixedData.matchInfo.team2.shortName,
        ]}
      ></InPageNavigation> */}
      {data.length <= 0 ? (
        <h1>....Loading</h1>
      ) : (
        <InPageNavigation
          teams={[
            data.matchInfo.team1.shortName,
            data.matchInfo.team2.shortName,
          ]}
        >
          {data.matchInfo.team1.playerDetails.map((data, i) => (
            <div key={i} className="text-xl m-5">
              <h1>{data.fullName}</h1>
              <h3 className="opacity-50"> {data.role}</h3>
            </div>
          ))}

          {data.matchInfo.team2.playerDetails.map((data, i) => (
            <div key={i} className="text-xl m-5">
              <h1>{data.fullName}</h1>
              <h3 className="opacity-50"> {data.role}</h3>
            </div>
          ))}
        </InPageNavigation>
      )}
    </>
  );
};

export default MatchDetails;
